"""Trace-to-SSA conversion and verification-condition storage."""

from __future__ import annotations

import re
from collections import OrderedDict
from dataclasses import dataclass

import z3

from .horn import HornProgram, HornRule
from .normalize import flatten_and, mk_and, substitute_many

DEFAULT_MAX_SSA_CACHE_STEPS = 65_536


@dataclass(frozen=True)
class StateVersion:
    step: int
    relation: z3.FuncDeclRef
    variables: tuple[z3.ExprRef, ...]


@dataclass(frozen=True)
class VCStep:
    step: int
    rule: HornRule
    constraint: z3.BoolRef
    source_state: StateVersion | None
    destination_state: StateVersion | None
    fresh_rule_vars: tuple[z3.ExprRef, ...]


@dataclass(frozen=True)
class VerificationCondition:
    """An SSA-encoded CHC trace, analogous to BndExpl::getSSA output."""

    trace: tuple[HornRule, ...]
    steps: tuple[VCStep, ...]

    @property
    def formula(self) -> z3.BoolRef:
        return mk_and(step.constraint for step in self.steps)

    @property
    def rule_ids(self) -> tuple[int, ...]:
        return tuple(rule.rule_id for rule in self.trace)

    def to_smt2(self) -> str:
        """Render this trace SSA as replayable SMT-LIB2.

        Each SSA step is asserted separately so the trace structure remains easy
        to inspect. The comments are metadata only and do not affect replay in
        Z3 or another SMT-LIB2 solver.
        """
        comments = [
            "; generated by pyhorn-bounded-explorer",
            f"; trace-length: {len(self.trace)}",
            "; rule-ids: " + " ".join(str(rule_id) for rule_id in self.rule_ids),
        ]
        comments.extend(
            f"; step {index}: {rule.short()}"
            for index, rule in enumerate(self.trace)
        )

        solver = z3.Solver()
        for step in self.steps:
            solver.add(step.constraint)
        return "\n".join(comments) + "\n" + solver.to_smt2()


class BndExplSmtDumpBuilder:
    """Build the compact SSA formula used by the original ``bnd/expl`` dumps.

    The explorer's internal VC deliberately keeps explicit rule-local and state
    variables because that representation is convenient for caching.  The C++
    dump format is more compact: source arguments are substituted with the
    previous state, each non-query destination gets fresh ``__bnd_var_N``
    symbols, and remaining rule-local variables use ``__loc_var_N``.
    """

    def __init__(self, program: HornProgram) -> None:
        self.program = program

    def build_formula(self, trace: tuple[HornRule, ...]) -> z3.BoolRef:
        if not trace:
            raise ValueError("an SMT dump requires a non-empty trace")

        bind_index = 0
        local_index = 0
        current_state: tuple[z3.ExprRef, ...] | None = None
        constraints: list[z3.BoolRef] = []

        for step_index, rule in enumerate(trace):
            # Z3 expressions overload ``__eq__`` to construct formulas.  Use
            # stable AST identifiers for Python mapping and membership rather
            # than relying on expression-object equality.
            substitutions: dict[int, tuple[z3.ExprRef, z3.ExprRef]] = {}
            links: list[z3.BoolRef] = []

            if rule.src_relation is None:
                if current_state is not None:
                    raise ValueError(
                        "fact rule encountered after the first trace step"
                    )
            else:
                if current_state is None or len(rule.src_args) != len(current_state):
                    raise ValueError(
                        f"trace is disconnected at step {step_index}: {rule.short()}"
                    )
                for argument, state_var in zip(
                    rule.src_args, current_state, strict=True
                ):
                    if _is_rule_constant(argument):
                        previous = substitutions.get(argument.get_id())
                        if previous is None:
                            substitutions[argument.get_id()] = (
                                argument,
                                state_var,
                            )
                        else:
                            links.append(previous[1] == state_var)
                    else:
                        links.append(argument == state_var)

            if rule.dst_relation in self.program.query_relations:
                destination_state = None
            else:
                destination_vars: list[z3.ExprRef] = []
                for argument in rule.dst_args:
                    destination_vars.append(
                        z3.Const(f"__bnd_var_{bind_index}", argument.sort())
                    )
                    bind_index += 1
                destination_state = tuple(destination_vars)

                for argument, state_var in zip(
                    rule.dst_args, destination_state, strict=True
                ):
                    if (
                        _is_rule_constant(argument)
                        and argument.get_id() not in substitutions
                    ):
                        substitutions[argument.get_id()] = (argument, state_var)
                    else:
                        # This covers unchanged source variables, expressions in
                        # relation arguments, and duplicate destination variables.
                        links.append(argument == state_var)

            for variable in rule.rule_vars:
                if variable.get_id() in substitutions:
                    continue
                substitutions[variable.get_id()] = (
                    variable,
                    z3.Const(f"__loc_var_{local_index}", variable.sort()),
                )
                local_index += 1

            for item in (*flatten_and(rule.body), *links):
                constraints.append(
                    substitute_many(item, substitutions.values())
                )

            current_state = destination_state

        if trace[-1].dst_relation not in self.program.query_relations:
            raise ValueError("trace does not end in a query relation")
        return mk_and(constraints)

    def to_smt2(
        self,
        trace: tuple[HornRule, ...],
        *,
        bound: int,
        result: str,
    ) -> str:
        formula = self.build_formula(trace)
        declarations = _smt_declarations(formula)
        sections = [
            "; bnd/expl SMT dump",
            f"; bound: {bound}",
            f"; result: {result}",
            "",
        ]
        if declarations:
            sections.extend(declarations)
            sections.append("")
        sections.append(f"(assert {formula.sexpr()})")
        sections.append("(check-sat)")
        return "\n".join(sections) + "\n"


@dataclass(frozen=True)
class SSAConstructionStatistics:
    cached_steps: int
    cached_states: int
    cache_hits: int
    cache_misses: int
    cache_evictions: int


class VerificationConditionBuilder:
    """Build and cache deterministic positional SSA rule instances.

    For a fixed ``HornProgram``, the SSA expression for a rule occurrence is
    determined by ``(rule_id, step_index)``. Keeping this cache on the explorer
    avoids rebuilding the same Z3 AST when sibling traces share rule positions
    or when increasing bounds revisit a prefix.
    """

    def __init__(
        self,
        program: HornProgram,
        *,
        max_cached_steps: int | None = DEFAULT_MAX_SSA_CACHE_STEPS,
    ) -> None:
        if max_cached_steps is not None and max_cached_steps < 1:
            raise ValueError("max_cached_steps must be positive or None")
        self.program = program
        self.max_cached_steps = max_cached_steps
        self._step_cache: OrderedDict[tuple[int, int], VCStep] = OrderedDict()
        self._state_cache: OrderedDict[tuple[int, int], StateVersion] = OrderedDict()
        self._cache_hits = 0
        self._cache_misses = 0
        self._cache_evictions = 0

    @property
    def statistics(self) -> SSAConstructionStatistics:
        return SSAConstructionStatistics(
            cached_steps=len(self._step_cache),
            cached_states=len(self._state_cache),
            cache_hits=self._cache_hits,
            cache_misses=self._cache_misses,
            cache_evictions=self._cache_evictions,
        )

    def _remember_step(self, key: tuple[int, int], step: VCStep) -> None:
        self._step_cache[key] = step
        self._step_cache.move_to_end(key)
        if (
            self.max_cached_steps is not None
            and len(self._step_cache) > self.max_cached_steps
        ):
            self._step_cache.popitem(last=False)
            self._cache_evictions += 1

    def _remember_state(self, key: tuple[int, int], state: StateVersion) -> None:
        self._state_cache[key] = state
        self._state_cache.move_to_end(key)
        if (
            self.max_cached_steps is not None
            and len(self._state_cache) > self.max_cached_steps
        ):
            self._state_cache.popitem(last=False)
            self._cache_evictions += 1

    def _state_version(
        self, relation: z3.FuncDeclRef, step_index: int
    ) -> StateVersion:
        key = (relation.get_id(), step_index)
        cached = self._state_cache.get(key)
        if cached is not None:
            self._state_cache.move_to_end(key)
            return cached
        state = StateVersion(
            step=step_index,
            relation=relation,
            variables=tuple(
                z3.Const(
                    f"__state_{step_index}_{_safe_name(relation.name())}_{i}",
                    relation.domain(i),
                )
                for i in range(relation.arity())
            ),
        )
        self._remember_state(key, state)
        return state

    def build_step(self, rule: HornRule, step_index: int) -> VCStep:
        key = (rule.rule_id, step_index)
        cached = self._step_cache.get(key)
        if cached is not None:
            self._cache_hits += 1
            self._step_cache.move_to_end(key)
            return cached

        self._cache_misses += 1
        source_state = (
            None
            if rule.src_relation is None
            else self._state_version(rule.src_relation, step_index)
        )
        destination_state = (
            None
            if rule.dst_relation in self.program.query_relations
            else self._state_version(rule.dst_relation, step_index + 1)
        )

        fresh_vars = tuple(
            z3.Const(
                f"__rule_{rule.rule_id}_step_{step_index}_{i}_{_safe_name(var.decl().name())}",
                var.sort(),
            )
            for i, var in enumerate(rule.rule_vars)
        )
        substitutions = tuple(zip(rule.rule_vars, fresh_vars, strict=True))

        # Construct the complete rule/state-linking formula first and perform a
        # single Z3 substitution. The original implementation substituted the
        # body and every relation argument independently, which amplified the
        # Python/C API overhead for wide relations.
        constraints: list[z3.BoolRef] = [rule.body]
        if source_state is not None:
            if len(rule.src_args) != len(source_state.variables):
                raise ValueError(f"source arity mismatch in {rule.short()}")
            constraints.extend(
                lhs == rhs
                for lhs, rhs in zip(
                    rule.src_args, source_state.variables, strict=True
                )
            )
        if destination_state is not None:
            if len(rule.dst_args) != len(destination_state.variables):
                raise ValueError(f"destination arity mismatch in {rule.short()}")
            constraints.extend(
                lhs == rhs
                for lhs, rhs in zip(
                    rule.dst_args, destination_state.variables, strict=True
                )
            )

        raw_constraint = mk_and(constraints)
        step_constraint = z3.simplify(
            substitute_many(raw_constraint, substitutions)
        )
        step = VCStep(
            step=step_index,
            rule=rule,
            constraint=step_constraint,
            source_state=source_state,
            destination_state=destination_state,
            fresh_rule_vars=fresh_vars,
        )
        self._remember_step(key, step)
        return step

    def build_prefix(self, trace: tuple[HornRule, ...]) -> VerificationCondition:
        """Build a connected SSA prefix that may end at a non-query relation.

        Used directly by trace-guided candidate mining, which needs to solve
        prefixes that stop mid-program (at whatever relation it is sampling
        states for) rather than only complete ENTRY-to-query traces.
        """

        if not trace:
            raise ValueError("a verification condition requires a non-empty trace")

        current_state: StateVersion | None = None
        steps: list[VCStep] = []
        for step_index, rule in enumerate(trace):
            if rule.src_relation is None:
                if current_state is not None:
                    raise ValueError(
                        "fact rule encountered after the first trace step"
                    )
            elif (
                current_state is None
                or current_state.relation.get_id() != rule.src_relation.get_id()
            ):
                raise ValueError(
                    f"trace is disconnected at step {step_index}: {rule.short()}"
                )

            step = self.build_step(rule, step_index)
            steps.append(step)
            current_state = step.destination_state

        return VerificationCondition(trace=trace, steps=tuple(steps))

    def build(self, trace: tuple[HornRule, ...]) -> VerificationCondition:
        """Build a complete ENTRY-to-query verification condition."""

        vc = self.build_prefix(trace)
        if trace[-1].dst_relation not in self.program.query_relations:
            raise ValueError("trace does not end in a query relation")
        return vc


def _is_rule_constant(expr: z3.ExprRef) -> bool:
    return (
        z3.is_const(expr)
        and expr.decl().kind() == z3.Z3_OP_UNINTERPRETED
    )


def _collect_uninterpreted_declarations(
    expr: z3.ExprRef,
) -> tuple[z3.FuncDeclRef, ...]:
    found: dict[tuple[str, tuple[str, ...], str], z3.FuncDeclRef] = {}
    stack: list[z3.ExprRef] = [expr]
    while stack:
        current = stack.pop()
        if z3.is_quantifier(current):
            stack.append(current.body())
            continue
        if not z3.is_app(current):
            continue
        declaration = current.decl()
        if declaration.kind() == z3.Z3_OP_UNINTERPRETED:
            key = (
                str(declaration.name()),
                tuple(declaration.domain(i).sexpr() for i in range(declaration.arity())),
                declaration.range().sexpr(),
            )
            found[key] = declaration
        stack.extend(current.children())
    return tuple(found[key] for key in sorted(found))


_SIMPLE_SYMBOL = re.compile(
    r"^[A-Za-z~!@$%^&*+=<>.?/_-][A-Za-z0-9~!@$%^&*+=<>.?/_-]*$"
)
_RESERVED_SYMBOLS = {
    "!",
    "_",
    "as",
    "BINARY",
    "DECIMAL",
    "exists",
    "HEXADECIMAL",
    "forall",
    "let",
    "match",
    "NUMERAL",
    "par",
    "STRING",
}


def _smt_symbol(name: object) -> str:
    rendered = str(name)
    if _SIMPLE_SYMBOL.fullmatch(rendered) and rendered not in _RESERVED_SYMBOLS:
        return rendered
    if "|" not in rendered and "\\" not in rendered:
        return f"|{rendered}|"
    # Extremely unusual names containing characters forbidden inside quoted
    # SMT-LIB symbols fall back to Z3's canonical printer.
    return z3.Const(rendered, z3.IntSort()).sexpr()


def _smt_declarations(expr: z3.ExprRef) -> list[str]:
    declarations: list[str] = []
    for declaration in _collect_uninterpreted_declarations(expr):
        domains = " ".join(
            declaration.domain(i).sexpr() for i in range(declaration.arity())
        )
        declarations.append(
            f"(declare-fun {_smt_symbol(declaration.name())} "
            f"({domains}) {declaration.range().sexpr()})"
        )
    return declarations


def _safe_name(name: object) -> str:
    rendered = str(name)
    return "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in rendered)


def build_verification_condition(
    program: HornProgram, trace: tuple[HornRule, ...]
) -> VerificationCondition:
    """Build one VC without retaining a cross-call cache.

    ``BoundedExplorer`` owns a persistent ``VerificationConditionBuilder`` and
    therefore reuses positional SSA steps. This convenience function preserves
    the original stateless public API for callers constructing an isolated VC.
    """
    return VerificationConditionBuilder(program).build(trace)
