"""Trace-to-SSA conversion and verification-condition storage."""

from __future__ import annotations

from dataclasses import dataclass

import z3

from .horn import HornProgram, HornRule
from .normalize import mk_and, substitute_many


@dataclass(frozen=True)
class StateVersion:
    step: int
    relation: z3.FuncDeclRef
    variables: tuple[z3.ExprRef, ...]


@dataclass(frozen=True)
class VCStep:
    step: int
    rule: HornRule
    constraint: z3.BoolRef
    source_state: StateVersion | None
    destination_state: StateVersion | None
    fresh_rule_vars: tuple[z3.ExprRef, ...]


@dataclass(frozen=True)
class VerificationCondition:
    """An SSA-encoded CHC trace, analogous to BndExpl::getSSA output."""

    trace: tuple[HornRule, ...]
    steps: tuple[VCStep, ...]

    @property
    def formula(self) -> z3.BoolRef:
        return mk_and(step.constraint for step in self.steps)

    @property
    def rule_ids(self) -> tuple[int, ...]:
        return tuple(rule.rule_id for rule in self.trace)

    def to_smt2(self) -> str:
        """Render this trace SSA as replayable SMT-LIB2.

        Each SSA step is asserted separately so the trace structure remains easy
        to inspect. The comments are metadata only and do not affect replay in
        Z3 or another SMT-LIB2 solver.
        """
        comments = [
            "; generated by pyhorn-bounded-explorer",
            f"; trace-length: {len(self.trace)}",
            "; rule-ids: " + " ".join(str(rule_id) for rule_id in self.rule_ids),
        ]
        comments.extend(
            f"; step {index}: {rule.short()}"
            for index, rule in enumerate(self.trace)
        )

        solver = z3.Solver()
        for step in self.steps:
            solver.add(step.constraint)
        return "\n".join(comments) + "\n" + solver.to_smt2()


@dataclass(frozen=True)
class SSAConstructionStatistics:
    cached_steps: int
    cache_hits: int
    cache_misses: int


class VerificationConditionBuilder:
    """Build and cache deterministic positional SSA rule instances.

    For a fixed ``HornProgram``, the SSA expression for a rule occurrence is
    determined by ``(rule_id, step_index)``. Keeping this cache on the explorer
    avoids rebuilding the same Z3 AST when sibling traces share rule positions
    or when increasing bounds revisit a prefix.
    """

    def __init__(self, program: HornProgram) -> None:
        self.program = program
        self._step_cache: dict[tuple[int, int], VCStep] = {}
        self._state_cache: dict[tuple[z3.FuncDeclRef, int], StateVersion] = {}
        self._cache_hits = 0
        self._cache_misses = 0

    @property
    def statistics(self) -> SSAConstructionStatistics:
        return SSAConstructionStatistics(
            cached_steps=len(self._step_cache),
            cache_hits=self._cache_hits,
            cache_misses=self._cache_misses,
        )

    def _state_version(
        self, relation: z3.FuncDeclRef, step_index: int
    ) -> StateVersion:
        key = (relation, step_index)
        cached = self._state_cache.get(key)
        if cached is not None:
            return cached
        state = StateVersion(
            step=step_index,
            relation=relation,
            variables=tuple(
                z3.Const(
                    f"__state_{step_index}_{_safe_name(relation.name())}_{i}",
                    relation.domain(i),
                )
                for i in range(relation.arity())
            ),
        )
        self._state_cache[key] = state
        return state

    def build_step(self, rule: HornRule, step_index: int) -> VCStep:
        key = (rule.rule_id, step_index)
        cached = self._step_cache.get(key)
        if cached is not None:
            self._cache_hits += 1
            return cached

        self._cache_misses += 1
        source_state = (
            None
            if rule.src_relation is None
            else self._state_version(rule.src_relation, step_index)
        )
        destination_state = (
            None
            if rule.dst_relation in self.program.query_relations
            else self._state_version(rule.dst_relation, step_index + 1)
        )

        fresh_vars = tuple(
            z3.Const(
                f"__rule_{rule.rule_id}_step_{step_index}_{i}_{_safe_name(var.decl().name())}",
                var.sort(),
            )
            for i, var in enumerate(rule.rule_vars)
        )
        substitutions = tuple(zip(rule.rule_vars, fresh_vars, strict=True))

        # Construct the complete rule/state-linking formula first and perform a
        # single Z3 substitution. The original implementation substituted the
        # body and every relation argument independently, which amplified the
        # Python/C API overhead for wide relations.
        constraints: list[z3.BoolRef] = [rule.body]
        if source_state is not None:
            if len(rule.src_args) != len(source_state.variables):
                raise ValueError(f"source arity mismatch in {rule.short()}")
            constraints.extend(
                lhs == rhs
                for lhs, rhs in zip(
                    rule.src_args, source_state.variables, strict=True
                )
            )
        if destination_state is not None:
            if len(rule.dst_args) != len(destination_state.variables):
                raise ValueError(f"destination arity mismatch in {rule.short()}")
            constraints.extend(
                lhs == rhs
                for lhs, rhs in zip(
                    rule.dst_args, destination_state.variables, strict=True
                )
            )

        raw_constraint = mk_and(constraints)
        step_constraint = z3.simplify(
            substitute_many(raw_constraint, substitutions)
        )
        step = VCStep(
            step=step_index,
            rule=rule,
            constraint=step_constraint,
            source_state=source_state,
            destination_state=destination_state,
            fresh_rule_vars=fresh_vars,
        )
        self._step_cache[key] = step
        return step

    def build(self, trace: tuple[HornRule, ...]) -> VerificationCondition:
        if not trace:
            raise ValueError("a verification condition requires a non-empty trace")

        current_state: StateVersion | None = None
        steps: list[VCStep] = []
        for step_index, rule in enumerate(trace):
            if rule.src_relation is None:
                if current_state is not None:
                    raise ValueError(
                        "fact rule encountered after the first trace step"
                    )
            elif (
                current_state is None
                or current_state.relation != rule.src_relation
            ):
                raise ValueError(
                    f"trace is disconnected at step {step_index}: {rule.short()}"
                )

            step = self.build_step(rule, step_index)
            steps.append(step)
            current_state = step.destination_state

        if trace[-1].dst_relation not in self.program.query_relations:
            raise ValueError("trace does not end in a query relation")
        return VerificationCondition(trace=trace, steps=tuple(steps))


def _safe_name(name: object) -> str:
    rendered = str(name)
    return "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in rendered)


def build_verification_condition(
    program: HornProgram, trace: tuple[HornRule, ...]
) -> VerificationCondition:
    """Build one VC without retaining a cross-call cache.

    ``BoundedExplorer`` owns a persistent ``VerificationConditionBuilder`` and
    therefore reuses positional SSA steps. This convenience function preserves
    the original stateless public API for callers constructing an isolated VC.
    """
    return VerificationConditionBuilder(program).build(trace)
